### ISSUE TITLE
Indentation issues with BBCode code and Litedown

### ISSUE THREAD

**Issue by AlfredoRamos** [s9e/TextFormatter#170] opened 2021-07-21 20:46 UTC
Hi :wave: 

Someone reported me that by having Litedown enabled (from my Markdown extension for phpBB), the snippets using the `[code]` BBCode have some indentation issues.

Code example:

```
[code]
using System;

class Program{
	static void Main(string[] args){
		Console.Write("hello");

		if (1 == 1){
			Console.WriteLine("test");
		}
	}
}
[/code]
```

Result:

![Screenshot_20210721_151613](https://user-images.githubusercontent.com/4165935/126554261-cf6fa39b-7833-4495-84c5-05d06d0c8ba0.png)

<details>
<summary>Same example as above with Markdown disabled</summary>

![Screenshot_20210721_152803](https://user-images.githubusercontent.com/4165935/126555675-b54f5cc6-249c-4124-95cc-10aa46cc9efa.png)

</details>

<details>
<summary>This is how it looks using Markdown</summary>

![Screenshot_20210721_152223](https://user-images.githubusercontent.com/4165935/126555030-83c4dbd1-d84b-4e01-be01-a4794e7346b2.png)

~~~
```
using System;

class Program{
	static void Main(string[] args){
		Console.Write("hello");

		if (1 == 1){
			Console.WriteLine("test");
		}
	}
}
```
~~~

</details>

Inspecting the generated XML code I see that, when Litedown is enabled, it contains `<i>` tags.

`[code]` BBCode with Litedown enabled

```xml
<CODE><s>[code]</s>using System;

class Program{
	static void Main(string[] args){
		Console.Write("hello");

<i>	</i>	if (1 == 1){
<i>	</i>		Console.WriteLine("test");
<i>	</i>	}
<i>	</i>}
}<e>[/code]</e></CODE>
```

`[code]` BBCode with Litedown disabled

```xml
<CODE><s>[code]</s>using System;

class Program{
	static void Main(string[] args){
		Console.Write("hello");
		
		if (1 == 1){
			Console.WriteLine("test");
		}
	}
}<e>[/code]</e></CODE>
```

My setup:
- phpBB 3.3.4 (s9e/text-formatter 2.8.4)
- Nginx 1.21.1
- PostgreSQL 13.2
- PHP 8.0.8

P.S.: I'm not sure if this is related to #169, that's why I decided to opened this new issue.

**Comment by JoshyPHP** [comment] 2021-07-21 21:07
You're correct, this is the same issue. Some block-level spans of text that need to be ignored because of Markdown rules end up being ignored inside of code blocks created by BBCodes. The workaround is to use Litedown code blocks.

I might close #169 as a dupe of this one because this is the best formatted bug report I have seen in a while. 👍

**Closed** 2021-07-22 20:56 UTC
Labels: Bother, Won't fix
