### ISSUE TITLE
Quoted text affects the rest of the message

### ISSUE THREAD

**Issue by rxu** [s9e/TextFormatter#224] opened 2023-09-30 05:17 UTC
I'm not sure if it's TF, but reporting in case it is.
In phpBB, if you put unparsed BBCode part in `quote` tags, text outside the quote will be formatted like it was put in BBCode. F.e. in this case
```
[quote]
<r><B><s>[b]</s><SIZE size="150"><s>
[/quote]

This text shouldn't be bold.
```
`This text shouldn't be bold.` is being renderer bold.

In this case
```
[quote]<r><B><s>[b]</s><SIZE size="150"><s>[size=150]</s>[/quote]

This text shouldn't be the size of 150.
```

`This text shouldn't be the size of 150.` is being rendered in size of 150.

![image](https://github.com/s9e/TextFormatter/assets/212322/8b8f53a4-bdb8-42be-a406-142245f8f280)

Also a combination:

```
[quote]<r><B><s>[b]</s><SIZE size="150"><s>[size=150]</s>[/quote]

This text shouldn't be the size of 150.


[quote]
<r><B><s>[b]</s><SIZE size="150"><s>
[/quote]

This text shouldn't be bold.
```

![image](https://github.com/s9e/TextFormatter/assets/212322/4dd0effe-8f2c-4ab4-90ca-018d691ec6b5)

**Comment by JoshyPHP** [comment] 2023-09-30 16:33
> if you put unparsed BBCode part in `quote` tags

In this case, it's really the `[b]` part of that XML that's important. It works the same way if you use something like `[quote][b]..[/quote]..`

To answer your question, it's technically not a bug; The behaviour is expected. It's governed by the [AutoReopenFormattingElements](https://s9etextformatter.readthedocs.io/Rules/Rules_generators/#autoreopenformattingelements) which reopens formatting elements when they forcibly closed by a parent element being closed. In that context, a formatting element is any markup that maps to a [formatting element as defined in HTML](https://html.spec.whatwg.org/multipage/parsing.html#formatting) or a `span` element that has only `class` and/or `style` attributes. Incidentally, the rule about formatting elements is modeled after HTML's, where `<p><b>bold<p>still bold` gets parsed as `<p><b>bold</b></p><p><b>still bold</b></p>`.

The behaviour can be disabled globally by removing the rules generator like so:
```php
$configurator->rulesGenerator->remove('AutoReopenFormattingElements');
```

The downside is that some users just want to select a big chunk of text such as an entire quote and change its colour or whatever, and without that rule they have to be carefully to apply the styling markup *inside* of the block markup. Some people also try to select a span of text that starts in a block and ends in another block. That rule makes it possible. Personally I'm not fond of it though.

**Comment by JoshyPHP** [comment] 2023-09-30 16:39
I forgot to add, you can also disable that rule selectively on each tag. You can do it in the BBCode definition itself if it's easier to edit. For instance:
```[SIZE={FONTSIZE} #autoReopen=false]{TEXT}[/SIZE]```

**Comment by rxu** [comment] 2023-09-30 16:51
Thanks for the extended explanation. Just out of interest then, this behavior doesn't affect `code` BBcode, is `#autoReopen` disabled for it by default?

**Comment by JoshyPHP** [comment] 2023-09-30 17:08
A single `<code>` would be a formatting element but the `[code]` BBCode isn't rendered as a formatting element, it uses a `<pre><code>` combo that makes it a block element.

**Closed** 2023-09-30 17:21 UTC
